/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'workload',
    path: '/workload',
    component: 'layout.base',
    meta: {
      title: 'workload',
      i18nKey: 'route.workload'
    },
    children: [
      {
        name: 'workload_detail',
        path: '/workload/detail/:id',
        component: 'view.workload_detail',
        meta: {
          title: 'workload_detail',
          i18nKey: 'route.workload_detail',
          hideInMenu: true
        }
      },
      {
        name: 'workload_experiment',
        path: '/workload/experiment/:id',
        component: 'view.workload_experiment',
        meta: {
          title: 'workload_experiment',
          i18nKey: 'route.workload_experiment',
          hideInMenu: true
        }
      },
      {
        name: 'workload_internship',
        path: '/workload/internship/:id',
        component: 'view.workload_internship',
        meta: {
          title: 'workload_internship',
          i18nKey: 'route.workload_internship',
          hideInMenu: true
        }
      },
      {
        name: 'workload_list',
        path: '/workload/list',
        component: 'view.workload_list',
        meta: {
          title: 'workload_list',
          i18nKey: 'route.workload_list'
        }
      },
      {
        name: 'workload_online',
        path: '/workload/online/:id',
        component: 'view.workload_online',
        meta: {
          title: '网络课程教学工作量',
          i18nKey: 'route.workload_online',
          hideInMenu: true
        }
      },
      {
        name: 'workload_paper',
        path: '/workload/paper/:id',
        component: 'view.workload_paper',
        meta: {
          title: 'workload_paper',
          i18nKey: 'route.workload_paper'
        }
      },
      {
        name: 'workload_theory',
        path: '/workload/theory/:id',
        component: 'view.workload_theory',
        meta: {
          title: 'workload_theory',
          i18nKey: 'route.workload_theory',
          hideInMenu: true
        }
      }
    ]
  }
];
